In [2]:
import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta

from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler

import matplotlib.pyplot as plt

In [4]:
import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta

# Defining missing variables to make the cell runnable
students = [f"STU{i:04d}" for i in range(1, 1501)] # Example student IDs
subjects = ["Math", "Science", "History", "Physics", "Chemistry", "Biology", "English", "CS", "ML", "Python", "DBMS", "CN"] # Example subjects
start_date = datetime(2026, 4, 1) # Example start date
end_date = datetime(2026, 4, 30) # Example end date
days = (end_date - start_date).days + 1 # Number of days

# Initialize df if it doesn't exist. This cell assumes 'df' is already populated
# with genuine records, but for demonstration, we create an empty one if not found.
if 'df' not in locals() and 'df' not in globals():
    df = pd.DataFrame(columns=[
        "Student_ID", "Date", "Time", "Subject", "Location", "Device_ID",
        "Latitude", "Longitude", "Attendance_Status", "Actual_Label"
    ])

proxy_records = []

for i in range(600):
    random_student = random.choice(students)
    subject = random.choice(subjects)
    date = start_date + timedelta(days=random.randint(0, days-1))

    suspicious_time = datetime(date.year, date.month, date.day, random.choice([9,10,11,12,14,15]), random.randint(0, 2))

    # Same device fraud
    shared_device = f"DEV_PROXY_{random.randint(1, 20)}"

    # Location mismatch
    wrong_lat = 30.5000 + np.random.normal(0, 0.001)
    wrong_lon = 78.0000 + np.random.normal(0, 0.001)

    proxy_records.append({
        "Student_ID": random_student,
        "Date": date.strftime("%Y-%m-%d"),
        "Time": suspicious_time.strftime("%H:%M:%S"),
        "Subject": subject,
        "Location": f"Room_{subject}",
        "Device_ID": shared_device,
        "Latitude": wrong_lat,
        "Longitude": wrong_lon,
        "Attendance_Status": "Present",
        "Actual_Label": "Proxy"
    })

proxy_df = pd.DataFrame(proxy_records)

df = pd.concat([df, proxy_df], ignore_index=True)

df = df.sample(frac=1, random_state=42).reset_index(drop=True)

df.head()

/tmp/ipykernel_6035/2468528969.py:52: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, proxy_df], ignore_index=True)

,Student_ID,Date,Time,Subject,Location,Device_ID,Latitude,Longitude,Attendance_Status,Actual_Label
0,STU0256,2026-04-10,14:01:00,English,Room_English,DEV_PROXY_7,30.499850,78.000289,Present,Proxy
1,STU0623,2026-04-30,12:00:00,Chemistry,Room_Chemistry,DEV_PROXY_7,30.499631,77.999463,Present,Proxy
2,STU0910,2026-04-17,12:01:00,Python,Room_Python,DEV_PROXY_7,30.501419,78.000073,Present,Proxy
3,STU0403,2026-04-04,09:00:00,DBMS,Room_DBMS,DEV_PROXY_1,30.499961,78.000848,Present,Proxy
4,STU1216,2026-04-16,09:00:00,Math,Room_Math,DEV_PROXY_2,30.501376,77.997748,Present,Proxy

In [5]:
df.shape

(600, 10)

In [7]:
df["Actual_Label"].value_counts()

Actual_Label
Proxy    600
Name: count, dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Student_ID         600 non-null    object
 1   Date               600 non-null    object
 2   Time               600 non-null    object
 3   Subject            600 non-null    object
 4   Location           600 non-null    object
 5   Device_ID          600 non-null    object
 6   Latitude           600 non-null    float64
 7   Longitude          600 non-null    float64
 8   Attendance_Status  600 non-null    object
 9   Actual_Label       600 non-null    object
dtypes: float64(2), object(8)
memory usage: 47.0+ KB

In [9]:
df.to_csv("proxy_attendance_dataset.csv", index=False)

In [10]:
from google.colab import files
files.download("proxy_attendance_dataset.csv")